steps:

## Build container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/proyecto-terraform-301015/nginx:latest', '.' ]

## Push container image to gcr
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/proyecto-terraform-301015/nginx:latest']
